commonLabels:
  object: postgres

global:
  postgresql:
    auth:
      # Password for the "postgres" admin user (overrides auth.postgresPassword)
      postgresPassword: Weops123!

primary:
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
  initdb:
    scripts:
      auth.sql: |
        CREATE ROLE weops WITH LOGIN PASSWORD 'Weops123!';
        GRANT pg_monitor TO weops;

readReplicas:
  name: secondary
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 800Mi

