persistence:
  enabled: false

commonLabels:
  object: postgres

global:
  postgresql:
    password: Weops123!
  pgpool:
    adminPassword: Weops123!

postgresql:
  nodeSelector:
    node-role: worker
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
  initdbScripts:
    auth.sql: |
      CREATE ROLE weops WITH LOGIN PASSWORD 'Weops123!';
      GRANT pg_monitor TO weops;

pgpool:
  initdbScripts: |
    CREATE ROLE weops WITH LOGIN PASSWORD 'Weops123!';
    GRANT pg_monitor TO weops;