commonLabels:
  object: postgres

global:
  postgresql:
    auth:
      # Password for the "postgres" admin user (overrides auth.postgresPassword)
      postgresPassword: Weops123!

primary:
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false

readReplicas:
  name: secondary
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
