commonLabels:
  object: postgres

global:
  postgresql:
    auth:
      # Password for the "postgres" admin user (overrides auth.postgresPassword)
      postgresPassword: Weops123!

postgresqlSharedPreloadLibraries: "pgaudit, pg_stat_statements"

primary:
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 300Mi
  podSecurityContext:
    fsGroup: 0
  containerSecurityContext:
    runAsUser: 0


readReplicas:
  name: secondary
  nodeSelector:
    node-role: worker
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 300Mi
  podSecurityContext:
    fsGroup: 0
  containerSecurityContext:
    runAsUser: 0